name: emergency_management_app
description: A comprehensive emergency management application with alerting, mitigation, and relief modules.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  go_router: ^12.1.3
  
  # Firebase Integration
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  
  # State Management & Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # HTTP & Networking
  http: ^1.1.0
  dio: ^5.4.0
  
  # Permissions & Device Access
  permission_handler: ^11.1.0
  flutter_bluetooth_serial: ^0.4.0
  
  # UI Enhancements
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  flutter_local_notifications: ^16.3.0
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700